export default {
  fontFamily: [
    "Notion Sans",
    "Inter",
    "-apple-system",
    "BlinkMacSystemFont",
    '"Segoe UI"',
    "Roboto",
    '"Helvetica Neue"',
    "Arial",
    "sans-serif",
  ].join(","),
  h1: {
    fontSize: "2.5rem",
    fontWeight: 700,
    lineHeight: 1.1,
    letterSpacing: "-1px",
  },
  h2: {
    fontSize: "1.625rem",
    fontWeight: 700,
    lineHeight: 1.23,
    letterSpacing: "-0.625px",
  },
  h3: {
    fontSize: "1.375rem",
    fontWeight: 700,
    lineHeight: 1.27,
    letterSpacing: "-0.25px",
  },
  h4: {
    fontSize: "1.25rem",
    fontWeight: 600,
    lineHeight: 1.4,
    letterSpacing: "-0.125px",
  },
  h5: {
    fontSize: "1.125rem",
    fontWeight: 600,
    lineHeight: 1.4,
    letterSpacing: 0,
  },
  h6: {
    fontSize: "1rem",
    fontWeight: 600,
    lineHeight: 1.4,
    letterSpacing: 0,
  },
  display1: {
    fontSize: "4rem",
    fontWeight: 700,
    lineHeight: 1.0,
    letterSpacing: "-2.125px",
  },
  display2: {
    fontSize: "3.375rem",
    fontWeight: 700,
    lineHeight: 1.04,
    letterSpacing: "-1.875px",
  },
  body1: {
    fontSize: "1rem",
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: 0,
  },
  body2: {
    fontSize: "0.9375rem",
    fontWeight: 400,
    lineHeight: 1.33,
    letterSpacing: 0,
  },
  button: {
    textTransform: "none",
    fontWeight: 500,
    fontSize: "1rem",
    lineHeight: 1.5,
    letterSpacing: 0,
  },
  caption: {
    fontSize: "0.875rem",
    fontWeight: 400,
    lineHeight: 1.43,
    letterSpacing: 0,
  },
  overline: {
    fontSize: "0.75rem",
    fontWeight: 600,
    lineHeight: 1.33,
    letterSpacing: "0.125px",
    textTransform: "uppercase",
  },
};
