export default {
  fontFamily: [
    'Inter',
    '-apple-system',
    'BlinkMacSystemFont',
    '"Segoe UI"',
    'Roboto',
    '"Helvetica Neue"',
    'Arial',
    'sans-serif',
  ].join(','),
  h1: { fontSize: '2rem', fontWeight: 600, lineHeight: 1.3 },
  h2: { fontSize: '1.75rem', fontWeight: 600, lineHeight: 1.35 },
  h3: { fontSize: '1.5rem', fontWeight: 500, lineHeight: 1.4 },
  h4: { fontSize: '1.25rem', fontWeight: 500, lineHeight: 1.4 },
  h5: { fontSize: '1.1rem', fontWeight: 500, lineHeight: 1.45 },
  h6: { fontSize: '1rem', fontWeight: 500, lineHeight: 1.5 },
  body1: { fontSize: '0.875rem', lineHeight: 1.5 },
  body2: { fontSize: '0.8125rem', lineHeight: 1.5 },
  button: { textTransform: 'none', fontWeight: 500 },
  caption: { fontSize: '0.75rem', lineHeight: 1.5 },
};
