export default {
  fontFamily: [
    '"Plus Jakarta Sans"',
    "-apple-system",
    "BlinkMacSystemFont",
    '"Segoe UI"',
    "Roboto",
    '"Helvetica Neue"',
    "Arial",
    "sans-serif",
  ].join(","),
  h1: {
    fontFamily: [
      '"Plus Jakarta Sans"',
      "-apple-system",
      "BlinkMacSystemFont",
      '"Segoe UI"',
      "Roboto",
      "sans-serif",
    ].join(","),
    fontSize: "2rem",
    fontWeight: 700,
    lineHeight: 1.25,
    letterSpacing: "-0.02em",
  },
  h2: {
    fontFamily: [
      '"Plus Jakarta Sans"',
      "-apple-system",
      "BlinkMacSystemFont",
      '"Segoe UI"',
      "Roboto",
      "sans-serif",
    ].join(","),
    fontSize: "1.625rem",
    fontWeight: 700,
    lineHeight: 1.3,
    letterSpacing: "-0.015em",
  },
  h3: {
    fontFamily: [
      '"Plus Jakarta Sans"',
      "-apple-system",
      "BlinkMacSystemFont",
      '"Segoe UI"',
      "Roboto",
      "sans-serif",
    ].join(","),
    fontSize: "1.375rem",
    fontWeight: 650,
    lineHeight: 1.35,
    letterSpacing: "-0.01em",
  },
  h4: {
    fontFamily: [
      '"Plus Jakarta Sans"',
      "-apple-system",
      "BlinkMacSystemFont",
      '"Segoe UI"',
      "Roboto",
      "sans-serif",
    ].join(","),
    fontSize: "1.125rem",
    fontWeight: 650,
    lineHeight: 1.4,
    letterSpacing: "-0.005em",
  },
  h5: {
    fontFamily: [
      '"Plus Jakarta Sans"',
      "-apple-system",
      "BlinkMacSystemFont",
      '"Segoe UI"',
      "Roboto",
      "sans-serif",
    ].join(","),
    fontSize: "1rem",
    fontWeight: 600,
    lineHeight: 1.45,
    letterSpacing: 0,
  },
  h6: {
    fontFamily: [
      '"Plus Jakarta Sans"',
      "-apple-system",
      "BlinkMacSystemFont",
      '"Segoe UI"',
      "Roboto",
      "sans-serif",
    ].join(","),
    fontSize: "0.9375rem",
    fontWeight: 600,
    lineHeight: 1.5,
    letterSpacing: 0,
  },
  body1: { fontSize: "0.875rem", lineHeight: 1.6 },
  body2: { fontSize: "0.8125rem", lineHeight: 1.55 },
  button: { textTransform: "none", fontWeight: 600 },
  caption: { fontSize: "0.75rem", lineHeight: 1.5, letterSpacing: "0.01em" },
};
